"""
CityBus Enterprise Platform - ESG & Environmental Emission Calculator
File: backend/services/co2_emission_calculator.py

Calculates Greenhouse Gas (GHG) Scope 1 & Scope 2 carbon footprint,
computes passenger-km emissions saved compared to private ICE transport,
and outputs environmental sustainability certificates.
"""

from typing import Dict, List, Any
from models import Bus, Route, Ticket, db


class CO2EmissionCalculator:
    """Calculates municipal transit carbon mitigation and EV fleet offset metrics."""

    # Emission factors (grams CO2 per passenger-kilometer)
    PRIVATE_CAR_G_PKM = 171.0
    TWO_WHEELER_G_PKM = 82.0
    DIESEL_BUS_G_PKM = 68.0
    ELECTRIC_BUS_G_PKM = 14.0 # Indian grid average electricity generation factor

    @staticmethod
    def calculate_fleet_esg_impact() -> Dict[str, Any]:
        """Aggregates total carbon emissions avoided across all operational routes."""
        buses = Bus.query.all()
        total_ev_buses = sum(1 for b in buses if b.fuel_type == "Electric")
        total_diesel_buses = sum(1 for b in buses if b.fuel_type == "Diesel")

        total_tickets = Ticket.query.count()
        total_pkm_estimated = total_tickets * 12.5 # Average 12.5 km journey distance

        # Carbon generated by public bus fleet vs private car baseline
        private_transport_co2_kg = (total_pkm_estimated * CO2EmissionCalculator.PRIVATE_CAR_G_PKM) / 1000.0
        bus_transit_co2_kg = (total_pkm_estimated * CO2EmissionCalculator.DIESEL_BUS_G_PKM) / 1000.0
        net_co2_saved_kg = max(0.0, private_transport_co2_kg - bus_transit_co2_kg)

        trees_equivalent = int(net_co2_saved_kg / 21.77) # 1 tree absorbs ~21.77 kg CO2/year

        return {
            "total_fleet_vehicles": len(buses),
            "electric_buses_count": total_ev_buses,
            "diesel_buses_count": total_diesel_buses,
            "ev_fleet_penetration_pct": round((total_ev_buses / max(1, len(buses))) * 100.0, 1),
            "total_passenger_km_served": round(total_pkm_estimated, 1),
            "total_co2_avoided_kg": round(net_co2_saved_kg, 1),
            "total_co2_avoided_metric_tons": round(net_co2_saved_kg / 1000.0, 2),
            "mature_trees_planted_equivalent": trees_equivalent,
            "fuel_liters_saved": round(net_co2_saved_kg / 2.31, 1)
        }
